sonar.projectKey=RoksanaDrozd_BudgetApp-Sonar
sonar.organization=roksanadrozd
sonar.projectName=BudgetApp-Sonar
sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.spec.ts,**/*.spec.js