spring.application.name=PASIR_drozd_roksana
spring.config.import=optional:file:.env[.properties]

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE:drozd_roksana_gi_spring}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER:user-rd}
spring.datasource.password=${MYSQL_PASSWORD:haslo}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# GraphQL
spring.graphql.http.path=/graphql
spring.graphql.schema.file-extensions=.graphql,.graphqls,.gqls

app.jwt.secret=${JWT_SECRET}